### ISSUE TITLE
Tracking Issue for 2021 October Releases

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky-enhancement-proposals#22]
- [x] [bluesky v1.8.1](https://github.com/bluesky/bluesky/releases/tag/v1.8.1)
- [x] [event-model v1.17.2](https://github.com/bluesky/event-model/releases/tag/v1.17.2)
- [x] [bluesky-darkframes v0.5.0](https://github.com/bluesky/bluesky-darkframes/pull/33)
- [x] ophyd
- [x] suitcase-*
  - [x] [suitcase-csv v0.3.0](https://github.com/bluesky/suitcase-csv/releases/tag/v0.3.0)
  - [x] [suitcase-dataexchange v0.1.0](https://github.com/bluesky/suitcase-dataexchange/releases/tag/v0.1.0)
  - [x] [suitcase-json-metadata v0.2.1](https://github.com/bluesky/suitcase-json-metadata/releases/tag/v0.2.1)
  - [x] [suitcase-jsonl v0.2.2](https://github.com/bluesky/suitcase-jsonl/releases/tag/v0.2.2)
  - [x] [suitcase-mongo v0.3.1](https://github.com/bluesky/suitcase-mongo/releases/tag/v0.3.1)
  - [x] [suitcase-msgpack v0.3.0](https://github.com/bluesky/suitcase-msgpack/releases/tag/v0.3.0)
  - [x] [suitcase-nxsas v0.1.0](https://github.com/bluesky/suitcase-nxsas/releases/tag/v0.1.0)
  - [x] [suitcase-specfile v0.2.4](https://github.com/bluesky/suitcase-specfile/releases/tag/v0.2.4)
- [x] NSLS-II/nslsii -- no changes since v0.2.1
- [x] bluesky-adaptive -- no changes since v0.2.0
- [x] [bluesky-kafka v0.6.0](https://github.com/bluesky/bluesky-kafka/pull/35)
- [x] [bluesky-cartpole v0.1.0](https://github.com/bluesky/bluesky-cartpole/pull/9)
- [x] [databroker v1.2.4](https://github.com/bluesky/databroker/releases/tag/v1.2.4)
- [x] [databroker-pack v0.3.1](https://github.com/bluesky/databroker-pack/releases/tag/v0.3.1)
- [x] [area-detector-handlers](https://github.com/bluesky/area-detector-handlers/compare/v0.0.8...master) - no major changes since v0.0.8 (just CI update)
- [x] [NSLS-II/nsls2-detector-handlers](https://github.com/NSLS-II/nsls2-detector-handlers/tags) - no new changes since 2020
- [x] tiled v0.1.0a40
- [x] [queueserver v0.0.7](https://github.com/bluesky/bluesky-queueserver/releases/tag/v0.0.7)
- [x] [httpserver v0.0.2](https://github.com/bluesky/bluesky-httpserver/releases/tag/v0.0.2)
- [x] [bluesky-widgets v0.0.10](https://github.com/bluesky/bluesky-widgets/releases/tag/v0.0.10)
- [x] bluesky-live -- No important changes since last release
- [x] hklpy -- no changes since v1.0.1
- [x] [scientific-python-cookiecutter v0.1.0](https://github.com/NSLS-II/scientific-python-cookiecutter/pull/106)

**Comment by mrakitin** [comment]
I grabbed all the releases from the `bluesky` org with https://gist.github.com/mrakitin/c26a93e6ff190aa1232f2377ec892ad3 (uses https://pygithub.readthedocs.io). That's what we have:

  - [x] [bluesky v1.8.1](https://github.com/bluesky/bluesky/releases/tag/v1.8.1)
  - [x] [bluesky-darkframes v0.5.0](https://github.com/bluesky/bluesky-darkframes/releases/tag/v0.5.0)
  - [x] [bluesky-httpserver v0.0.2](https://github.com/bluesky/bluesky-httpserver/releases/tag/v0.0.2)
  - [x] [bluesky-queueserver v0.0.7](https://github.com/bluesky/bluesky-queueserver/releases/tag/v0.0.7)
  - [x] [databroker v1.2.4](https://github.com/bluesky/databroker/releases/tag/v1.2.4)
  - [x] [databroker-pack v0.3.1](https://github.com/bluesky/databroker-pack/releases/tag/v0.3.1)
  - [x] [event-model v1.17.2](https://github.com/bluesky/event-model/releases/tag/v1.17.2)
  - [x] [hklpy v1.0.1](https://github.com/bluesky/hklpy/releases/tag/v1.0.1)
  - [x] [ophyd v1.6.3](https://github.com/bluesky/ophyd/releases/tag/v1.6.3)
  - [x] [suitcase-csv v0.3.0](https://github.com/bluesky/suitcase-csv/releases/tag/v0.3.0)
  - [x] [suitcase-dataexchange v0.1.0](https://github.com/bluesky/suitcase-dataexchange/releases/tag/v0.1.0)
  - [x] [suitcase-json-metadata v0.2.1](https://github.com/bluesky/suitcase-json-metadata/releases/tag/v0.2.1)
  - [x] [suitcase-jsonl v0.2.2](https://github.com/bluesky/suitcase-jsonl/releases/tag/v0.2.2)
  - [x] [suitcase-mongo v0.3.1](https://github.com/bluesky/suitcase-mongo/releases/tag/v0.3.1)
  - [x] [suitcase-msgpack v0.3.0](https://github.com/bluesky/suitcase-msgpack/releases/tag/v0.3.0)
  - [x] [suitcase-nxsas v0.1.0](https://github.com/bluesky/suitcase-nxsas/releases/tag/v0.1.0)
  - [x] [suitcase-specfile v0.2.4](https://github.com/bluesky/suitcase-specfile/releases/tag/v0.2.4)
  - [x] [yaqc-bluesky v2021.9.0](https://github.com/bluesky/yaqc-bluesky/releases/tag/v2021.9.0)
